server:
  port: 9999

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: api
            uri: lb://api-service
            predicates:
            - Path=/**
    loadbalancer:
      eager-load:
        clients: api-service
  threads:
    virtual:
      enabled: true

gateway:
  api-uris: http://localhost:8080,http://localhost:8081