name: Publish rinha-gateway Docker image

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Generate Images
        run: ./gradlew bootBuildImage -p gateway

      - name: Tag Images
        run: docker tag rinha-gateway:0.0.1-SNAPSHOT marcusdacoregio/rinha-gateway:latest

      - name: Push Images
        run: docker push marcusdacoregio/rinha-gateway:latest
